name: Update Packages

on:
  workflow_dispatch: # Only manual trigger

permissions:
  contents: write

jobs:
  update:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Xcode packages
        run: |
          xcodebuild -resolvePackageDependencies

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(deps): Update Swift package dependencies'
          commit_user_name: GitHub Action
